"""Read and audit Milestone 4 scenario exports; no model training is performed.

A scenario directory contains inventory_summary.csv, inventory_weekly.csv,
inventory_products.csv, inventory_daily.csv, and simulation_config.json.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

FILE_MAP = {
    "summary": "inventory_summary.csv",
    "weekly": "inventory_weekly.csv",
    "products": "inventory_products.csv",
    "daily": "inventory_daily.csv",
}
NUMERIC_TOL = 1e-5


def require_columns(frame: pd.DataFrame, columns: list[str], source: str) -> None:
    missing = sorted(set(columns) - set(frame.columns))
    if missing:
        raise ValueError(f"{source}: missing columns {missing}")


def load_scenario(folder: Path, *, details: bool = True) -> dict:
    """Read exports. If details=False, summary alone is sufficient for portfolio UI."""
    folder = Path(folder)
    summary_file = folder / FILE_MAP["summary"]
    if not summary_file.is_file():
        raise FileNotFoundError(f"Expected {summary_file}")
    summary = pd.read_csv(summary_file)
    require_columns(summary, ["model", "weekly_budget", "fill_rate_pct", "unmet_units",
                              "stockout_sku_days", "replenishment_spend",
                              "contribution_proxy", "demand_proxy_units"], str(summary_file))
    if summary.empty or summary.model.isna().any() or summary.model.duplicated().any():
        raise ValueError(f"{summary_file}: models must be nonempty and unique")
    budget_values = pd.to_numeric(summary["weekly_budget"], errors="coerce").dropna().unique()
    if len(budget_values) > 1:
        raise ValueError(f"{summary_file}: inconsistent weekly budgets")
    budget = float(budget_values[0]) if len(budget_values) == 1 else None
    result = {"folder": folder, "summary": summary, "budget": budget,
              "weekly": None, "products": None, "daily": None, "config": None}
    config_path = folder / "simulation_config.json"
    if config_path.is_file():
        result["config"] = json.loads(config_path.read_text(encoding="utf-8"))
    if details:
        for key in ("weekly", "products", "daily"):
            path = folder / FILE_MAP[key]
            if not path.is_file():
                raise FileNotFoundError(f"Missing {path}. Re-run simulator with this --output-dir.")
            result[key] = pd.read_csv(path)
    return result


def discover_scenarios(root: Path) -> list[dict]:
    """Discover directories generated by simulate_inventory.py; skip incomplete folders."""
    results = []
    output_root = Path(root) / "outputs"
    if not output_root.is_dir():
        return results
    for folder in sorted(output_root.glob("inventory*")):
        if folder.is_dir() and (folder / FILE_MAP["summary"]).is_file():
            results.append(load_scenario(folder, details=False))
    return results


def scenario_label(scenario: dict) -> str:
    budget = scenario["budget"]
    label = "Unconstrained" if budget is None else f"Budget {budget:,.0f}/week"
    return f"{label} · {scenario['folder'].name}"


def _close(left, right, label, *, tolerance=NUMERIC_TOL) -> None:
    a = np.asarray(left, dtype=float)
    b = np.asarray(right, dtype=float)
    if a.shape != b.shape or not np.allclose(a, b, rtol=1e-8, atol=tolerance, equal_nan=False):
        delta = float(np.max(np.abs(a - b))) if a.size and a.shape == b.shape else float("nan")
        raise ValueError(f"{label}: accounting mismatch (max absolute difference {delta:.6g})")


def validate_scenario(scenario: dict) -> dict:
    """Raise ValueError on an accounting violation. Returns an audit summary."""
    summary = scenario["summary"]
    weekly = scenario["weekly"]
    products = scenario["products"]
    daily = scenario["daily"]
    if any(f is None for f in (weekly, products, daily)):
        raise ValueError("Detailed CSVs required for validation; reload with details=True")

    require_columns(daily, ["model", "node_id", "item_id", "store_id", "week", "d_num",
                            "demand_proxy", "fulfilled_units", "unmet_units", "stockout_day",
                            "received_units", "stock_before_demand", "ending_inventory",
                            "ordered_units", "order_spend", "forecast_7d"], "inventory_daily.csv")
    require_columns(weekly, ["model", "week", "demand_proxy_units", "fulfilled_units",
                             "unmet_units", "replenishment_spend", "replenishment_units",
                             "stockout_sku_days", "fill_rate_pct"], "inventory_weekly.csv")
    require_columns(products, ["model", "node_id", "item_id", "store_id", "demand_proxy_units",
                               "fulfilled_units", "unmet_units", "stockout_days",
                               "replenishment_spend", "replenishment_units"], "inventory_products.csv")
    require_columns(summary, ["model", "demand_proxy_units", "fulfilled_units", "unmet_units",
                              "replenishment_spend", "replenishment_units", "fill_rate_pct",
                              "stockout_sku_days"], "inventory_summary.csv")
    if daily.empty or weekly.empty or products.empty:
        raise ValueError("Empty simulation export")
    if daily.duplicated(["model", "node_id", "d_num"]).any():
        raise ValueError("Duplicate model/node/day records")
    if weekly.duplicated(["model", "week"]).any():
        raise ValueError("Duplicate model/week records")
    if products.duplicated(["model", "node_id"]).any():
        raise ValueError("Duplicate model/node records")
    if set(daily.model) != set(summary.model) or set(weekly.model) != set(summary.model) or set(products.model) != set(summary.model):
        raise ValueError("The exported files contain inconsistent model lists")
    for col in ("demand_proxy", "fulfilled_units", "unmet_units", "received_units",
                "stock_before_demand", "ending_inventory", "ordered_units", "order_spend"):
        a = pd.to_numeric(daily[col], errors="coerce").to_numpy()
        if not np.isfinite(a).all() or (a < -NUMERIC_TOL).any():
            raise ValueError(f"Invalid negative or non-finite daily values in {col}")

    _close(daily.demand_proxy, daily.fulfilled_units + daily.unmet_units, "Daily demand conservation")
    _close(daily.ending_inventory,
           daily.stock_before_demand - daily.fulfilled_units, "Daily inventory conservation")
    _close(daily.stockout_day.astype(int), (daily.unmet_units > NUMERIC_TOL).astype(int),
           "Stockout-day indicators", tolerance=0)

    ordered = daily.sort_values(["model", "node_id", "d_num"]).copy()
    previous_stock = ordered.groupby(["model", "node_id"]).ending_inventory.shift()
    followup = previous_stock.notna()
    _close(ordered.loc[followup, "stock_before_demand"],
           previous_stock[followup] + ordered.loc[followup, "received_units"],
           "Day-to-day inventory movement")

    # All models must experience the same observed demand at the same node/day.
    demand_spread = daily.groupby(["node_id", "d_num"]).demand_proxy.agg(["min", "max"])
    if ((demand_spread["max"] - demand_spread["min"]).abs() > NUMERIC_TOL).any():
        raise ValueError("Models received different observed demand")
    first_day = ordered.groupby(["model", "node_id"], as_index=False).first()
    first_day["initial_stock"] = first_day.stock_before_demand - first_day.received_units
    initial_spread = first_day.groupby("node_id").initial_stock.agg(["min", "max"])
    if ((initial_spread["max"] - initial_spread["min"]).abs() > NUMERIC_TOL).any():
        raise ValueError("Models started with different initial inventory")

    weekly_calc = daily.groupby(["model", "week"], as_index=False).agg(
        demand_proxy_units=("demand_proxy", "sum"),
        fulfilled_units=("fulfilled_units", "sum"), unmet_units=("unmet_units", "sum"),
        replenishment_spend=("order_spend", "sum"),
        replenishment_units=("ordered_units", "sum"),
        stockout_sku_days=("stockout_day", "sum"),
    )
    weekly_joined = weekly_calc.merge(weekly, on=["model", "week"], how="outer", validate="one_to_one",
                                      suffixes=("_calc", "_saved"), indicator=True)
    if (weekly_joined._merge != "both").any():
        raise ValueError("Weekly export has missing or extra model/week entries")
    for metric in ("demand_proxy_units", "fulfilled_units", "unmet_units",
                   "replenishment_spend", "replenishment_units", "stockout_sku_days"):
        _close(weekly_joined[f"{metric}_calc"], weekly_joined[f"{metric}_saved"], f"Weekly {metric}")
    calc_fill = 100 * weekly_calc.fulfilled_units / weekly_calc.demand_proxy_units.replace(0, np.nan)
    _close(calc_fill.to_numpy(), weekly_joined["fill_rate_pct"].to_numpy(),
           "Weekly fill rate")
    budget = scenario["budget"]
    if budget is not None and (weekly_calc.replenishment_spend > budget + NUMERIC_TOL).any():
        raise ValueError(f"Weekly purchasing budget {budget:,.2f} exceeded")

    prod_calc = daily.groupby(["model", "node_id"], as_index=False).agg(
        demand_proxy_units=("demand_proxy", "sum"), fulfilled_units=("fulfilled_units", "sum"),
        unmet_units=("unmet_units", "sum"), stockout_days=("stockout_day", "sum"),
        replenishment_spend=("order_spend", "sum"), replenishment_units=("ordered_units", "sum"),
    )
    prod_joined = prod_calc.merge(products, on=["model", "node_id"], how="outer", validate="one_to_one",
                                  suffixes=("_calc", "_saved"), indicator=True)
    if (prod_joined._merge != "both").any():
        raise ValueError("Product export has missing or extra model/node entries")
    for metric in ("demand_proxy_units", "fulfilled_units", "unmet_units", "stockout_days",
                   "replenishment_spend", "replenishment_units"):
        _close(prod_joined[f"{metric}_calc"], prod_joined[f"{metric}_saved"], f"Product {metric}")

    by_model = daily.groupby("model", as_index=False).agg(
        demand_proxy_units=("demand_proxy", "sum"), fulfilled_units=("fulfilled_units", "sum"),
        unmet_units=("unmet_units", "sum"), replenishment_spend=("order_spend", "sum"),
        replenishment_units=("ordered_units", "sum"), stockout_sku_days=("stockout_day", "sum"),
    )
    combined = by_model.merge(summary, on="model", how="outer", validate="one_to_one",
                              suffixes=("_calc", "_saved"), indicator=True)
    if (combined._merge != "both").any():
        raise ValueError("Summary has missing or extra models")
    for metric in ("demand_proxy_units", "fulfilled_units", "unmet_units", "replenishment_spend",
                   "replenishment_units", "stockout_sku_days"):
        _close(combined[f"{metric}_calc"], combined[f"{metric}_saved"], f"Portfolio {metric}")
    _close(100 * combined.fulfilled_units_calc / combined.demand_proxy_units_calc,
           combined.fill_rate_pct, "Portfolio fill rate")
    return {"models": len(summary), "nodes": int(daily.node_id.nunique()),
            "days": int(daily.d_num.nunique()), "weeks": int(daily.week.nunique()),
            "maximum_weekly_spend": float(weekly_calc.replenishment_spend.max()),
            "weekly_budget": budget, "rows_checked": len(daily)}


def compare_scenario_inputs(scenarios: list[dict]) -> dict:
    """Verify common observed demand and initial inventory across scenario exports."""
    if len(scenarios) < 2:
        return {"scenarios": len(scenarios), "checked_nodes_days": 0}
    base = scenarios[0]["daily"]
    if base is None:
        raise ValueError("Cross-scenario comparison needs detailed exports")
    base_model = sorted(base.model.unique())[0]
    base_frame = base.loc[base.model.eq(base_model),
                          ["node_id", "d_num", "demand_proxy", "stock_before_demand", "received_units"]]
    base_frame = base_frame.sort_values(["node_id", "d_num"]).reset_index(drop=True)
    keys = ["node_id", "d_num"]
    base_first = base_frame.drop_duplicates("node_id")
    base_initial = (base_first.stock_before_demand - base_first.received_units).to_numpy()
    for scenario in scenarios[1:]:
        frame = scenario["daily"]
        if set(frame.model.unique()) != set(base.model.unique()):
            raise ValueError(f"Scenario {scenario['folder'].name}: forecasting models differ")
        model = sorted(frame.model.unique())[0]
        other = frame.loc[frame.model.eq(model),
                          [*keys, "demand_proxy", "stock_before_demand", "received_units"]]
        other = other.sort_values(keys).reset_index(drop=True)
        if not base_frame[keys].equals(other[keys]):
            raise ValueError(f"Scenario {scenario['folder'].name}: SKU/day universe differs")
        _close(base_frame.demand_proxy, other.demand_proxy, "Cross-scenario observed demand")
        other_first = other.drop_duplicates("node_id")
        _close(base_initial, other_first.stock_before_demand - other_first.received_units,
               "Cross-scenario initial stock")
        a = scenarios[0].get("config") or {}
        b = scenario.get("config") or {}
        settings_a = a.get("settings") or {}
        settings_b = b.get("settings") or {}
        for key in ("lead_days", "safety_days", "initial_cover_weeks", "cost_ratio", "holding_rate", "order_fee", "seeds"):
            if key in settings_a and key in settings_b and settings_a[key] != settings_b[key]:
                raise ValueError(f"Scenario {scenario['folder'].name}: different {key}; not budget-only comparison")
    return {"scenarios": len(scenarios), "checked_nodes_days": len(base_frame)}


def product_differences(products: pd.DataFrame, model: str, baseline: str = "lightgbm") -> pd.DataFrame:
    """Per-SKU paired comparison. Positive `unmet_reduction_units` means less unmet demand."""
    if model == baseline:
        raise ValueError("Choose distinct models")
    require_columns(products, ["model", "item_id", "store_id", "demand_proxy_units", "unmet_units",
                               "stockout_days", "replenishment_spend"], "inventory_products.csv")
    keys = ["item_id", "store_id"]
    cols = keys + ["demand_proxy_units", "unmet_units", "stockout_days", "replenishment_spend"]
    left = products.loc[products.model.eq(baseline), cols].copy()
    right = products.loc[products.model.eq(model), cols].copy()
    if left.empty or right.empty:
        raise ValueError(f"Missing model {baseline} or {model} in product data")
    joined = left.merge(right, on=keys, how="outer", validate="one_to_one",
                        suffixes=("_baseline", "_model"), indicator=True)
    if (joined._merge != "both").any():
        raise ValueError("Models do not contain identical SKU-store combinations")
    _close(joined.demand_proxy_units_baseline, joined.demand_proxy_units_model,
           "Model product-level demand alignment")
    joined["unmet_reduction_units"] = joined.unmet_units_baseline - joined.unmet_units_model
    joined["stockout_days_avoided"] = joined.stockout_days_baseline - joined.stockout_days_model
    joined["spend_difference"] = joined.replenishment_spend_model - joined.replenishment_spend_baseline
    return joined.drop(columns="_merge").sort_values("unmet_reduction_units", ascending=False)
